background_animation:
  default: "None (default)"
  type: enum
  choices:
    - Links
    - Anemone
    - Hyperspace
  description: "Setting to choose the background animation of the site."

display_new_topic_badge:
  default: true
  type: bool
  description: "Show 'New!' badge next to new topics."

welcome_user_mesage:
  default: "Welcome back, "
  type: string
  description: "The welcome message of logged in users."

signup_messgae:
  default: "Join in on the conversation!"
  type: string
  description: "The signup messag eof logged out users."
