show_tsParticles_links_animation:
  default: false
  type: bool
  description: "Setting to enable/disable tsParticles' links animation."

#show_tsParticles_parallax_animation:
  #default: false
  #type: bool
  #description: "Setting to enable/disable tsParticles' links animation."
