background_animation:
  default: "None (default)"
  type: enum
  choices:
    - Links
    - Anemone
    - Hyperspace
  description: "Setting to choose the background animation of the site."

display_new_topic_badge:
  default: true
  type: bool
  description: "Show 'New!' badge next to new topics."
